#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\BCJ\Git\Xylophone_Hero\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/EDK
NON_CYG_XILINX_EDK_DIR = C:/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-7

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

XYLOPHONE_HERO_OUTPUT_DIR = xylophone_hero
XYLOPHONE_HERO_OUTPUT = $(XYLOPHONE_HERO_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

PPC405_1_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_1.elf

BRAMINIT_ELF_FILES =  $(XYLOPHONE_HERO_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0 $(XYLOPHONE_HERO_OUTPUT) 

ALL_USER_ELF_FILES = $(XYLOPHONE_HERO_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X c:/BCJ/Git/Xylophone_Hero/ -E c:/BCJ/Git/Xylophone_Hero/


LIBRARIES =  \
       ppc405_0/lib/libxil.a  \
       ppc405_1/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = ppc405_0_libsclean ppc405_1_libsclean 

PROGRAMCLEAN_TARGETS = xylophone_hero_programclean 

CORE_STATE_DEVELOPMENT_FILES = C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\lf_decode.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\neg_edge_detect.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\pipe_line_delay.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\special_svga_timing_generation.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\vp422_444_dup.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\ycrcb2rgb.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\line_buffer.vhd \
C:\BCJ\Git\Xylophone_Hero\pcores\video_capture_v1_01_b\hdl\vhdl\video_capture.vhd

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/ppc405_1_wrapper.ngc \
implementation/jtagppc_0_wrapper.ngc \
implementation/reset_block_wrapper.ngc \
implementation/plb_wrapper.ngc \
implementation/opb_wrapper.ngc \
implementation/plb2opb_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/i2c_wrapper.ngc \
implementation/video_capture_0_wrapper.ngc \
implementation/reset_split_wrapper.ngc \
implementation/and_gate_0_wrapper.ngc \
implementation/i2c_rst_or_wrapper.ngc \
implementation/white_color_wrapper.ngc \
implementation/black_color_wrapper.ngc \
implementation/white_count_wrapper.ngc \
implementation/black_count_wrapper.ngc \
implementation/calib_wrapper.ngc \
implementation/bw_wrapper.ngc \
implementation/clk_27_wrapper.ngc \
implementation/frame_wrapper.ngc \
implementation/game_mode_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION XYLOPHONE_HERO
#################################################################

XYLOPHONE_HERO_SOURCES = /cygdrive/c/BCJ/Git/Xylophone_Hero/xylophone_hero/src/xylophone_hero.c /cygdrive/c/BCJ/Git/Xylophone_Hero/xylophone_hero/src/uart.c /cygdrive/c/BCJ/Git/Xylophone_Hero/xylophone_hero/src/xi2c_l.c 

XYLOPHONE_HERO_HEADERS = /cygdrive/c//BCJ/Git/Xylophone_Hero/xylophone_hero/src/xylophone_hero.h /cygdrive/c//BCJ/Git/Xylophone_Hero/xylophone_hero/src/characters.h /cygdrive/c//BCJ/Git/Xylophone_Hero/xylophone_hero/src/uart.h /cygdrive/c//BCJ/Git/Xylophone_Hero/xylophone_hero/src/xi2c_l.h 

XYLOPHONE_HERO_CC = powerpc-eabi-gcc
XYLOPHONE_HERO_CC_SIZE = powerpc-eabi-size
XYLOPHONE_HERO_CC_OPT = -O2
XYLOPHONE_HERO_CFLAGS = 
XYLOPHONE_HERO_CC_SEARCH = # -B
XYLOPHONE_HERO_LIBPATH = -L./ppc405_0/lib/ # -L
XYLOPHONE_HERO_INCLUDES = -I./ppc405_0/include/  -Ixylophone_hero/src/ # -I
XYLOPHONE_HERO_LFLAGS = # -l
XYLOPHONE_HERO_LINKER_SCRIPT = 
XYLOPHONE_HERO_LINKER_SCRIPT_FLAG = #-Wl,-T -Wl,$(XYLOPHONE_HERO_LINKER_SCRIPT) 
XYLOPHONE_HERO_CC_DEBUG_FLAG =  -g 
XYLOPHONE_HERO_CC_PROFILE_FLAG = # -pg
XYLOPHONE_HERO_CC_GLOBPTR_FLAG= # -msdata=eabi
XYLOPHONE_HERO_CC_INFERRED_FLAGS= 
XYLOPHONE_HERO_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_START_ADDR=
XYLOPHONE_HERO_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
XYLOPHONE_HERO_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
XYLOPHONE_HERO_OTHER_CC_FLAGS= $(XYLOPHONE_HERO_CC_GLOBPTR_FLAG)  \
                  $(XYLOPHONE_HERO_CC_START_ADDR_FLAG) $(XYLOPHONE_HERO_CC_STACK_SIZE_FLAG) $(XYLOPHONE_HERO_CC_HEAP_SIZE_FLAG)  \
                  $(XYLOPHONE_HERO_CC_INFERRED_FLAGS)  \
                  $(XYLOPHONE_HERO_LINKER_SCRIPT_FLAG) $(XYLOPHONE_HERO_CC_DEBUG_FLAG) $(XYLOPHONE_HERO_CC_PROFILE_FLAG) 
