
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2 EDK_Jm.16
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_I2C_DEVICE_ID,
		XPAR_I2C_BASEADDR,
		XPAR_I2C_TEN_BIT_ADR,
		XPAR_I2C_GPO_WIDTH
	}
};


