
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2 EDK_Jm.16
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Definitions for driver OPBARB */
#define XPAR_XOPBARB_NUM_INSTANCES 1

/* Definitions for peripheral OPB */
#define XPAR_OPB_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_HIGHADDR 0x00000000
#define XPAR_OPB_DEVICE_ID 0
#define XPAR_OPB_NUM_MASTERS 1


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral RS232_UART_1 */
#define XPAR_RS232_UART_1_BASEADDR 0x40600000
#define XPAR_RS232_UART_1_HIGHADDR 0x4060FFFF
#define XPAR_RS232_UART_1_DEVICE_ID 0
#define XPAR_RS232_UART_1_BAUDRATE 9600
#define XPAR_RS232_UART_1_USE_PARITY 0
#define XPAR_RS232_UART_1_ODD_PARITY 0
#define XPAR_RS232_UART_1_DATA_BITS 8


/******************************************************************/


/* Canonical definitions for peripheral RS232_UART_1 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_RS232_UART_1_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_UARTLITE_0_HIGHADDR 0x4060FFFF
#define XPAR_UARTLITE_0_BAUDRATE 9600
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral I2C */
#define XPAR_I2C_DEVICE_ID 0
#define XPAR_I2C_BASEADDR 0x40800000
#define XPAR_I2C_HIGHADDR 0x4080FFFF
#define XPAR_I2C_TEN_BIT_ADR 0
#define XPAR_I2C_GPO_WIDTH 2


/******************************************************************/


/* Canonical definitions for peripheral I2C */
#define XPAR_IIC_0_DEVICE_ID XPAR_I2C_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0x40800000
#define XPAR_IIC_0_HIGHADDR 0x4080FFFF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 2


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 9

/* Definitions for peripheral WHITE_COLOR */
#define XPAR_WHITE_COLOR_BASEADDR 0x40000000
#define XPAR_WHITE_COLOR_HIGHADDR 0x400001FF
#define XPAR_WHITE_COLOR_DEVICE_ID 0
#define XPAR_WHITE_COLOR_INTERRUPT_PRESENT 0
#define XPAR_WHITE_COLOR_IS_DUAL 0


/* Definitions for peripheral BLACK_COLOR */
#define XPAR_BLACK_COLOR_BASEADDR 0x40000200
#define XPAR_BLACK_COLOR_HIGHADDR 0x400003FF
#define XPAR_BLACK_COLOR_DEVICE_ID 1
#define XPAR_BLACK_COLOR_INTERRUPT_PRESENT 0
#define XPAR_BLACK_COLOR_IS_DUAL 0


/* Definitions for peripheral WHITE_COUNT */
#define XPAR_WHITE_COUNT_BASEADDR 0x40000400
#define XPAR_WHITE_COUNT_HIGHADDR 0x400005FF
#define XPAR_WHITE_COUNT_DEVICE_ID 2
#define XPAR_WHITE_COUNT_INTERRUPT_PRESENT 0
#define XPAR_WHITE_COUNT_IS_DUAL 0


/* Definitions for peripheral BLACK_COUNT */
#define XPAR_BLACK_COUNT_BASEADDR 0x40000600
#define XPAR_BLACK_COUNT_HIGHADDR 0x400007FF
#define XPAR_BLACK_COUNT_DEVICE_ID 3
#define XPAR_BLACK_COUNT_INTERRUPT_PRESENT 0
#define XPAR_BLACK_COUNT_IS_DUAL 0


/* Definitions for peripheral CALIB */
#define XPAR_CALIB_BASEADDR 0x40000800
#define XPAR_CALIB_HIGHADDR 0x400009FF
#define XPAR_CALIB_DEVICE_ID 4
#define XPAR_CALIB_INTERRUPT_PRESENT 0
#define XPAR_CALIB_IS_DUAL 0


/* Definitions for peripheral BW */
#define XPAR_BW_BASEADDR 0x40000A00
#define XPAR_BW_HIGHADDR 0x40000BFF
#define XPAR_BW_DEVICE_ID 5
#define XPAR_BW_INTERRUPT_PRESENT 0
#define XPAR_BW_IS_DUAL 0


/* Definitions for peripheral CLK_27 */
#define XPAR_CLK_27_BASEADDR 0x40000C00
#define XPAR_CLK_27_HIGHADDR 0x40000DFF
#define XPAR_CLK_27_DEVICE_ID 6
#define XPAR_CLK_27_INTERRUPT_PRESENT 0
#define XPAR_CLK_27_IS_DUAL 0


/* Definitions for peripheral FRAME */
#define XPAR_FRAME_BASEADDR 0x40000E00
#define XPAR_FRAME_HIGHADDR 0x40000FFF
#define XPAR_FRAME_DEVICE_ID 7
#define XPAR_FRAME_INTERRUPT_PRESENT 0
#define XPAR_FRAME_IS_DUAL 0


/* Definitions for peripheral GAME_MODE */
#define XPAR_GAME_MODE_BASEADDR 0x40001000
#define XPAR_GAME_MODE_HIGHADDR 0x400011FF
#define XPAR_GAME_MODE_DEVICE_ID 8
#define XPAR_GAME_MODE_INTERRUPT_PRESENT 0
#define XPAR_GAME_MODE_IS_DUAL 0


/******************************************************************/


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xFFFE0000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xFFFFFFFF


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_PPC405_ID 0
#define XPAR_PPC405_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_PPC405_ISOCM_DCR_BASEADDR 0x00000010
#define XPAR_PPC405_ISOCM_DCR_HIGHADDR 0x00000013
#define XPAR_PPC405_DSOCM_DCR_BASEADDR 0x00000020
#define XPAR_PPC405_DSOCM_DCR_HIGHADDR 0x00000023
#define XPAR_PPC405_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_DETERMINISTIC_MULT 0
#define XPAR_PPC405_MMU_ENABLE 1
#define XPAR_PPC405_DCR_RESYNC 0
#define XPAR_PPC405_HW_VER "2.00.c"

/******************************************************************/

